// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.bikeshop.domain;

import com.springsource.bikeshop.domain.Product;
import com.springsource.bikeshop.domain.ProductDataOnDemand;
import com.springsource.bikeshop.domain.ProductRepository;
import com.springsource.bikeshop.domain.Supplier;
import com.springsource.bikeshop.domain.SupplierDataOnDemand;
import com.springsource.bikeshop.reference.ProductType;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProductDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductDataOnDemand: @Component;
    
    private Random ProductDataOnDemand.rnd = new SecureRandom();
    
    private List<Product> ProductDataOnDemand.data;
    
    @Autowired
    private SupplierDataOnDemand ProductDataOnDemand.supplierDataOnDemand;
    
    @Autowired
    ProductRepository ProductDataOnDemand.productRepository;
    
    public Product ProductDataOnDemand.getNewTransientProduct(int index) {
        Product obj = new Product();
        setDescription(obj, index);
        setImage(obj, index);
        setName(obj, index);
        setProductType(obj, index);
        setReleaseDate(obj, index);
        setSupplier(obj, index);
        setWeight(obj, index);
        return obj;
    }
    
    public void ProductDataOnDemand.setDescription(Product obj, int index) {
        String description = "description_" + index;
        if (description.length() > 250) {
            description = description.substring(0, 250);
        }
        obj.setDescription(description);
    }
    
    public void ProductDataOnDemand.setImage(Product obj, int index) {
        byte[] image = String.valueOf(index).getBytes();
        obj.setImage(image);
    }
    
    public void ProductDataOnDemand.setName(Product obj, int index) {
        String name = "name_" + index;
        if (name.length() > 25) {
            name = name.substring(0, 25);
        }
        obj.setName(name);
    }
    
    public void ProductDataOnDemand.setProductType(Product obj, int index) {
        ProductType productType = ProductType.class.getEnumConstants()[0];
        obj.setProductType(productType);
    }
    
    public void ProductDataOnDemand.setReleaseDate(Product obj, int index) {
        Date releaseDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setReleaseDate(releaseDate);
    }
    
    public void ProductDataOnDemand.setSupplier(Product obj, int index) {
        Supplier supplier = supplierDataOnDemand.getRandomSupplier();
        obj.setSupplier(supplier);
    }
    
    public void ProductDataOnDemand.setWeight(Product obj, int index) {
        BigDecimal weight = BigDecimal.valueOf(index);
        if (weight.compareTo(new BigDecimal("0.0")) == -1 || weight.compareTo(new BigDecimal("9.99")) == 1) {
            weight = new BigDecimal("9.99");
        }
        obj.setWeight(weight);
    }
    
    public Product ProductDataOnDemand.getSpecificProduct(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Product obj = data.get(index);
        Long id = obj.getId();
        return productRepository.findOne(id);
    }
    
    public Product ProductDataOnDemand.getRandomProduct() {
        init();
        Product obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return productRepository.findOne(id);
    }
    
    public boolean ProductDataOnDemand.modifyProduct(Product obj) {
        return false;
    }
    
    public void ProductDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = productRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Product' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Product>();
        for (int i = 0; i < 10; i++) {
            Product obj = getNewTransientProduct(i);
            try {
                productRepository.save(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            productRepository.flush();
            data.add(obj);
        }
    }
    
}
