// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.bikeshop.web;

import com.springsource.bikeshop.web.ProductBean;
import java.io.Serializable;

privileged aspect ProductBean_Roo_Serializable {
    
    declare parents: ProductBean implements Serializable;
    
    private static final long ProductBean.serialVersionUID = 1L;
    
}
